#!/bin/sh

declare -a LAST_BRANCHS

get_last_branchs() {
    LAST_CHECKOUTS=`git reflog | grep "checkout:" | head -n5 `

    IFS=$'\n'; array=($LAST_CHECKOUTS); unset IFS;

    for index in "${!array[@]}"; do
        words=(${array[$index]})
        LAST_BRANCHS+=(${words[7]})
    done
}

show_last_branchs() {
    echo ${LAST_BRANCHS[@]}
}

main() {
    get_last_branchs
    show_last_branchs
}

main
