#!/bin/sh

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

source "$SCRIPT_DIR"/helper/selectoption.sh

declare -a LAST_BRANCHS
declare CHOICE
MAX_HISTORY=5

get_last_branchs() {
    LAST_CHECKOUTS=`git reflog | grep "checkout:" | head -n$MAX_HISTORY`

    IFS=$'\n'; array=($LAST_CHECKOUTS); unset IFS;

    for index in "${!array[@]}"; do
        words=(${array[$index]})
        LAST_BRANCHS+=(${words[7]})
    done
}

check_parameters() {
    if [ ${#LAST_BRANCHS[@]} == 0 ]; then
        echo "No branch history found"
        exit 0
    elif [ "$1" != ""  ]; then
        git checkout ${LAST_BRANCHS[$1]}
    else
        start_selection
    fi
}

start_selection() {
    echo "Select one:"
    select_option "${LAST_BRANCHS[@]}"
    CHOICE="${LAST_BRANCHS[$?]}"
    git checkout $CHOICE
}

main() {
    get_last_branchs
    check_parameters $1
}

main $1
