#!/bin/sh

declare -a LAST_BRANCHS
MAX_HISTORY=5

get_last_branchs() {
    LAST_CHECKOUTS=`git reflog | grep "checkout:" | head -n$MAX_HISTORY`

    IFS=$'\n'; array=($LAST_CHECKOUTS); unset IFS;

    for index in "${!array[@]}"; do
        words=(${array[$index]})
        LAST_BRANCHS+=(${words[7]})
    done
}

check_parameters() {
    if [ "$1" != ""  ]; then
        git checkout ${LAST_BRANCHS[$1]}
    else
        show_last_branchs
    fi
}

show_last_branchs() {
    for i in "${!LAST_BRANCHS[@]}"; do
        printf '%s %s\n' "[$i]" "${LAST_BRANCHS[$i]}"
    done
}

main() {
    get_last_branchs
    check_parameters $1
}

main $1
